### ISSUE TITLE
Selam.

### ISSUE THREAD

**Issue by mbnl** [xosad/Insta-mass-account-creator#14]
Kendi bilgisayarım üzerinde wamp server ile denediğimde herhangi bir hata veya herhangi bir yanıt alamıyorum "Generating Instagram Account!" diyor ve işlem sonlanıyor bir Ubuntu sunucu üzerinde denediğimde SOCKS5 proxy eklediğimde ise şu yanıtı alıyorum `{"account_created": false, "errors": {"ip": ["The IP address you are using has been flagged as an open proxy. If you believe this to be incorrect, please visit http://help.instagram.com/"]}, "status": "ok", "error_type": "signup_block"}
`

**Comment by xosad** [comment]
### The answer is inside the response  ;

* `The IP address you are using has been flagged as an open proxy`

### use Residential SOCKS5 PROXIES

**Comment by beshoo** [comment]
@xosad actually it seems kind of impossible to create accounts nowadays. I am not sure if you can right now. 
since I test the cleanest proxy, not used before! and I get the same message!
Do you think we still can use this script?

**Comment by xosad** [comment]
@beshoo This script used to work 4-5 month ago, after the patch, i never re-checked the requests instagram made, i'll have a look i might be able to fix it :)

**Comment by beshoo** [comment]
I will let my self to ask you, could you please try it now, since i believe
instagram almost disabled all emal creation methods.

Even from the app it self. It is very difficult to create an account
nowadays

So, cold you please try it now, and remember the 2 request client id and
token, Instagram watch what the proxy you are working with.

And i advise you to add http proxy support since it dos not mater, at the
end it is a connection to Instagram.

Regard
